version: '3.8'

services:


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: w-eventPlanner
      POSTGRES_PASSWORD: w-eventPlannerPASSWORD
      POSTGRES_DB: w-eventPlanner
    volumes:
      - postgres_data:/var/lib/postgresql/data



volumes:
  postgres_data: