framework:
    mailer:
        envelope:
            sender: "noreply@spelunkers.xeanto.us"
        dsn: "%env(MAILER_DSN)%"
        headers:
            From: "Travel App - Spelunkers <noreply@spelunkers.xeanto.us>"
