import "../styles/globals.css"
import Layout from "../components/common/Layout"
// import type { DehydratedState } from "react-query"
import { SessionProvider } from "next-auth/react"
import { auth } from "@/auth"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  const session = await auth();
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {children}
          </SessionProvider>
      </body>
    </html>
  )
}
