# https://medium.com/hostspaceng/triggering-workflows-in-another-repository-with-github-actions-4f581f8e0ceb

name: Deploy to Staging

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

jobs:
  trigger:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy Repository
        run: |
          cp -a * /opt/appRoot/.

      - name: Rebuild Containers
        env:
          SERVER_NAME: "staging.spelunkers.rit.edu"
          APP_SECRET: ${{ secrets.APP_SECRET }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          CADDY_MERCURE_JWT_SECRET: "ChangeThisMercureHubJWTSecretKey"
          GITAPP_ID: ${{ secrets.GITAPP_ID }}
          GITAPP_SECRET: ${{ secrets.GITAPP_SECRET }}
          NEXTAUTH_URL: ${{ variables.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}

        run: |
          cd /opt/appRoot
          docker-compose down
          echo "Recreating PWA .env file"
          rm -f pwa/.env
          echo "NEXTAUTH_URL=${NEXTAUTH_URL}" >> pwa/.env
          echo "NEXTAUTH_SECRET=${NEXTAUTH_SECRET}" >> pwa/.env
          echo "GOOGLE_ID=${GOOGLE_ID}" >> pwa/.env
          echo "GOOGLE_SECRET=${GOOGLE_SECRET}" >> pwa/.env
          echo "APP_ENV=prod" >> api/.env
          docker-compose up -f compose.yaml -f compose.prod.yaml --build -d --force-recreate
